### ISSUE TITLE
Cannot install peewee

### ISSUE THREAD

**Issue by mindv0rtex** [winpython/winpython#205]
I am trying to install peewee on both WinPython 2 and 3. In both cases it complains about a missing sqlite3.h header file. Manually copying the official sqlite3.h header file to a mingwpy include folder makes the installation complain about the "undefined reference to `init_sqlite_ext'", at which point I gave up...

**Comment by stonebig** [comment]
Hi @mindv0rtex ,

I didn't do anythng special to sqlite3, it's the default Python.org install version.

Would it be possible that:
- sqlite3.h by default is never in a python 'standard' installation,
- you copied a recent sqlite3.h from sqlite.org, that may not match the sqlite3.dll of the python standard version,
- and so that a solution may that:
  . you download and compile with vs2010 (for python 3.4) the latest sqlite3,
  . you copy the obtained sqlite.dll to \python-3.4.3.amd64\DLLs
  . then retrying your initial attempt, it may work ?

**Comment by stonebig** [comment]
I may not have the good advice, maybe the real problem could be that you can't do that with mingwpy

**Comment by mindv0rtex** [comment]
oh well...

**Comment by stonebig** [comment]
or ask on stackoverflow, maybe a quicker bet

**Comment by mindv0rtex** [comment]
You can close this - it appears to be a peewee bug for Python 3. I could successfully install the sqlite3 extensions with mingwpy under WinPython 2.

**Comment by stonebig** [comment]
ok. I noticed also yesterday that a peewee wheel has just been created by Christoph Gohlke.
